# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_place_submitted_by'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bookmarked_places',
            field=models.ManyToManyField(related_name='users', related_query_name='user', to='places.Place', verbose_name='bookmarked places'),
        ),
    ]
