# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 15:01
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='rating')),
                ('rated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='rated at')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_rating', to='places.Place', verbose_name='place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_rating', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name_plural': 'place rating',
                'verbose_name': 'place rating',
            },
        ),
        migrations.AlterUniqueTogether(
            name='placerating',
            unique_together=set([('place', 'user')]),
        ),
    ]
