# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_auto_20170129_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='placerating',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
    ]
