# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='name')),
                ('slug', models.SlugField(max_length=20, verbose_name='slug')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent_category', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_children', to='places.PlaceCategory', verbose_name='parent category')),
            ],
            options={
                'verbose_name': 'place category',
                'verbose_name_plural': 'place categories',
            },
        ),
        migrations.AlterField(
            model_name='place',
            name='google_places_id',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Google API Place ID'),
        ),
    ]
