# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20161025_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placecategory',
            name='slug',
            field=models.SlugField(max_length=20, unique=True, verbose_name='slug'),
        ),
    ]
