# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-29 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20170129_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeimage',
            name='image_height',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='image height'),
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='image_width',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='image width'),
        ),
    ]
