# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-30 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20170129_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='places', related_query_name='place', to='places.PlaceCategory', verbose_name='categories'),
        ),
    ]
