# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20170130_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='google_maps_url',
            field=models.URLField(blank=True, verbose_name='Google Maps URL'),
        ),
        migrations.AddField(
            model_name='place',
            name='location_latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='place',
            name='location_longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='longitude'),
        ),
        migrations.AlterField(
            model_name='place',
            name='google_places_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='Google API Place ID'),
        ),
        migrations.AlterField(
            model_name='place',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='places', related_query_name='place', to='places.PlaceTag'),
        ),
    ]
