# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_auto_20170213_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeimage',
            name='google_place_photo_id',
            field=models.CharField(default=2, max_length=255, unique=True, verbose_name='Google API Place Photo ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='image_height',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='image height'),
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='image_width',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='image width'),
        ),
    ]
