# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_auto_20170213_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
    ]
