# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 17:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0009_auto_20170214_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_places', related_query_name='submitted_place', to=settings.AUTH_USER_MODEL, verbose_name='submitted by'),
        ),
    ]
