# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 14:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='comment')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_comment', to='places.Place', verbose_name='place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_comment', to=settings.AUTH_USER_MODEL, verbose_name='place')),
            ],
            options={
                'verbose_name': 'place comment',
                'verbose_name_plural': 'place comments',
            },
        ),
    ]
