# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-06 15:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placecomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_comment', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
