# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-29 23:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20161206_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placecomment',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_comments', related_query_name='place_comment', to='places.Place', verbose_name='place'),
        ),
    ]
